name: RandomItemChange
version: '1.0-SNAPSHOT'

main: me.voseraproject.randomItemChange.RandomItemChange
api-version: '1.21'
load: POSTWORLD

authors: [ m.alidmr ]
website: https://voseraproject.tr

softdepend: [PlaceholderAPI]

commands:
  ric:
    description: Main command for Random Item Change
    aliases: [randomitemchange]

permissions:
  ric.start:
    description: Permission to start the event
    default: op
  ric.stop:
    description: Permission to stop the event
    default: op
  ric.duration:
    description: Permission to change the event duration
    default: op
  ric.blacklist:
    description: Permission to manage the item blacklist
    default: op
  ric.reload:
    description: Permission to reload the plugin configuration
    default: op